import java.awt.Toolkit;
import java.awt.Image;
import javax.swing.JFrame;

public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new javax.swing.JPanel();
        pnlSide = new javax.swing.JPanel();
        pnlCenter = new javax.swing.JPanel();
        pnlNorth = new javax.swing.JPanel();
        pnlLogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlCenterControls = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Coffee Canvas");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(245, 245, 245));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/img/favicon.png")));
        setMinimumSize(new java.awt.Dimension(1194, 834));
        setResizable(false);

        pnlRoot.setLayout(new java.awt.BorderLayout());

        pnlSide.setBackground(new java.awt.Color(0, 0, 0));
        pnlSide.setPreferredSize(new java.awt.Dimension(492, 834));
        pnlRoot.add(pnlSide, java.awt.BorderLayout.WEST);

        pnlCenter.setBackground(new java.awt.Color(245, 245, 245));
        pnlCenter.setPreferredSize(new java.awt.Dimension(702, 834));

        javax.swing.GroupLayout pnlCenterLayout = new javax.swing.GroupLayout(pnlCenter);
        pnlCenter.setLayout(pnlCenterLayout);
        pnlCenterLayout.setHorizontalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlCenterLayout.setVerticalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
        );

        pnlRoot.add(pnlCenter, java.awt.BorderLayout.CENTER);

        pnlNorth.setBackground(new java.awt.Color(255, 0, 0));
        pnlNorth.setPreferredSize(new java.awt.Dimension(1194, 98));
        pnlNorth.setLayout(new java.awt.BorderLayout());

        pnlLogo.setBackground(new java.awt.Color(31, 31, 31));
        pnlLogo.setPreferredSize(new java.awt.Dimension(492, 98));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dan Labrador\\OneDrive - addu.edu.ph\\Documents\\CS 2136\\7 GUI\\univ-simple-pos-system\\src\\resources\\img\\logo.png")); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setPreferredSize(new java.awt.Dimension(480, 86));
        pnlLogo.add(jLabel1);

        pnlNorth.add(pnlLogo, java.awt.BorderLayout.WEST);

        pnlCenterControls.setBackground(new java.awt.Color(245, 245, 245));

        javax.swing.GroupLayout pnlCenterControlsLayout = new javax.swing.GroupLayout(pnlCenterControls);
        pnlCenterControls.setLayout(pnlCenterControlsLayout);
        pnlCenterControlsLayout.setHorizontalGroup(
            pnlCenterControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );
        pnlCenterControlsLayout.setVerticalGroup(
            pnlCenterControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        pnlNorth.add(pnlCenterControls, java.awt.BorderLayout.CENTER);

        pnlRoot.add(pnlNorth, java.awt.BorderLayout.NORTH);

        getContentPane().add(pnlRoot, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlCenterControls;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlNorth;
    private javax.swing.JPanel pnlRoot;
    private javax.swing.JPanel pnlSide;
    // End of variables declaration//GEN-END:variables
}
